<#
.SYNOPSIS
    One-shot setup for an ONI Together LAN test node.

.DESCRIPTION
    Role 'host'   : locate ONI, write Directory.Build.props.user, restore tools, build,
                    open firewall ports. The build auto-deploys to the dev mod folder.
    Role 'client' : locate ONI, open firewall ports, create the dev mod folder.
                    Binaries arrive via deploy-to-peer.ps1 from the host box.

.EXAMPLE
    .\bootstrap.ps1 -Role host
    .\bootstrap.ps1 -Role client -LanPort 8080
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][ValidateSet('host', 'client')][string]$Role,
    [int]$LanPort = 8080,
    [string]$OniPath,
    [switch]$SkipFirewall
)

$ErrorActionPreference = 'Stop'
$ONI_APPID = '457140'

function Info($m) { Write-Host "[bootstrap] $m" -ForegroundColor Cyan }
function Ok($m)   { Write-Host "[bootstrap] OK   $m" -ForegroundColor Green }
function Warn($m) { Write-Host "[bootstrap] WARN $m" -ForegroundColor Yellow }
function Die($m)  { Write-Host "[bootstrap] FAIL $m" -ForegroundColor Red; exit 1 }

# --- locate ONI -------------------------------------------------------------
function Find-Oni {
    if ($OniPath) {
        if (Test-Path (Join-Path $OniPath 'OxygenNotIncluded_Data\Managed')) { return $OniPath }
        Die "-OniPath '$OniPath' has no OxygenNotIncluded_Data\Managed"
    }
    $steam = (Get-ItemProperty 'HKCU:\Software\Valve\Steam' -ErrorAction SilentlyContinue).SteamPath
    if (-not $steam) { Die 'Steam not found in registry. Pass -OniPath explicitly.' }

    $libs = @($steam)
    $vdf = Join-Path $steam 'steamapps\libraryfolders.vdf'
    if (Test-Path $vdf) {
        # Grab every "path"  "<...>"  value; works for both old and new vdf layouts.
        Select-String -Path $vdf -Pattern '"path"\s+"(.+?)"' -AllMatches |
            ForEach-Object { $_.Matches } |
            ForEach-Object { $libs += $_.Groups[1].Value.Replace('\\', '\') }
    }
    foreach ($lib in ($libs | Select-Object -Unique)) {
        $candidate = Join-Path $lib 'steamapps\common\OxygenNotIncluded'
        if (Test-Path (Join-Path $candidate 'OxygenNotIncluded_Data\Managed')) { return $candidate }
    }
    Die "Could not find OxygenNotIncluded in any Steam library. Searched: $($libs -join '; ')"
}

$oni = Find-Oni
$managed = Join-Path $oni 'OxygenNotIncluded_Data\Managed'
Ok "ONI: $oni"

# Documents may be redirected (OneDrive) - use the shell folder, not $env:USERPROFILE.
$docs = [Environment]::GetFolderPath('MyDocuments')
$modsRoot = Join-Path $docs 'Klei\OxygenNotIncluded\mods'
$devFolder = Join-Path $modsRoot 'dev'
New-Item -ItemType Directory -Force -Path $devFolder | Out-Null
Ok "mod dev folder: $devFolder"

# --- warn about a conflicting Workshop install ------------------------------
$workshop = Join-Path $oni '..\..\workshop\content\457140' | Resolve-Path -ErrorAction SilentlyContinue
if ($workshop) {
    Warn "Steam Workshop content for ONI exists at: $workshop"
    Warn 'If "ONI Together" is subscribed there, DISABLE it in-game (Mods menu).'
    Warn 'Two copies of the mod = Harmony patches applied twice = false test results.'
}
foreach ($stale in @('oni_mp', 'ONI_MP_dev')) {
    $p = Join-Path $devFolder $stale
    if (Test-Path $p) { Warn "Stale dev mod present: $p  (old 'ONI_MP' name - remove it)" }
}

# --- firewall ---------------------------------------------------------------
if (-not $SkipFirewall) {
    $tcpPort = $LanPort + 1
    $isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
               ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
    if (-not $isAdmin) {
        Warn "Not elevated - skipping firewall rules. Re-run as Administrator, or allow manually:"
        Warn "  inbound UDP $LanPort   (Riptide session)"
        Warn "  inbound TCP $tcpPort   (save file transfer)"
    } else {
        foreach ($r in @(@{N="ONI Together UDP $LanPort"; P='UDP'; V=$LanPort},
                         @{N="ONI Together TCP $tcpPort"; P='TCP'; V=$tcpPort})) {
            if (-not (Get-NetFirewallRule -DisplayName $r.N -ErrorAction SilentlyContinue)) {
                New-NetFirewallRule -DisplayName $r.N -Direction Inbound -Action Allow `
                    -Protocol $r.P -LocalPort $r.V | Out-Null
            }
            Ok "firewall: inbound $($r.P) $($r.V)"
        }
        Warn 'TCP must be open. If it is blocked the mod silently falls back to the'
        Warn 'UDP chunk path, which is the bug-dense route (AUDIT.md #6).'
    }
}

# --- host-only: build ------------------------------------------------------
if ($Role -eq 'host') {
    $repo = Split-Path -Parent $PSScriptRoot
    $propsUser = Join-Path $repo 'Directory.Build.props.user'

    $xml = @"
<?xml version="1.0" encoding="utf-8"?>
<!-- generated by testing/bootstrap.ps1 - safe to edit -->
<Project>
	<PropertyGroup>
		<GameLibsFolder>$managed</GameLibsFolder>
		<ModFolder>$devFolder</ModFolder>
	</PropertyGroup>
</Project>
"@
    Set-Content -Path $propsUser -Value $xml -Encoding UTF8
    Ok "wrote $propsUser"

    $dotnet = Get-Command dotnet -ErrorAction SilentlyContinue
    if (-not $dotnet) {
        # Installed but not on PATH (happens in restricted/child shells) - use the default location.
        $known = 'C:\Program Files\dotnet'
        if (Test-Path (Join-Path $known 'dotnet.exe')) {
            $env:PATH = "$known;$env:PATH"
            $dotnet = Get-Command dotnet -ErrorAction SilentlyContinue
            Warn "dotnet was not on PATH; using $known for this session"
        }
    }
    if (-not $dotnet) { Die 'dotnet SDK not found. Install .NET SDK 8: winget install Microsoft.DotNet.SDK.8' }
    $sdks = (& dotnet --list-sdks) -join "`n"
    if ($sdks -notmatch '(?m)^8\.') { Warn "No .NET 8 SDK listed. Publicizer/ILRepack may fail.`n$sdks" }
    Ok "dotnet: $((& dotnet --version))"

    Push-Location $repo
    try {
        Info 'dotnet tool restore (assembly-publicizer, ILRepack)'
        & dotnet tool restore
        if ($LASTEXITCODE -ne 0) { Die 'dotnet tool restore failed' }

        Info 'dotnet build ONI_Together (this also copies the mod into the dev folder)'
        & dotnet build 'ONI_Together\ONI_Together.csproj' -c Debug
        if ($LASTEXITCODE -ne 0) {
            Warn 'Build failed. Common cause: the IDE/MSBuild has not yet picked up the'
            Warn 'PublicisedAssembly folder created on the first run. Run this script again.'
            Die 'build failed'
        }
    } finally { Pop-Location }

    $out = Join-Path $devFolder 'ONI_Together_dev'
    if (Test-Path (Join-Path $out 'ONI_Together.dll')) {
        Ok "deployed: $out"
    } else {
        Warn "Build succeeded but $out\ONI_Together.dll is missing - check ModFolder in Directory.Build.props.user"
    }
}

Write-Host ''
Ok "role '$Role' ready."
Write-Host @"

Next:
  1. Launch ONI on BOTH machines. Mods menu:
       - ENABLE  'Oxygen Not Included Together' (the dev one)
       - DISABLE any Workshop copy
  2. In the mod options set:
       Client LAN Ip   = $(if ($Role -eq 'host') { '<this box LAN IP>  (tell the client)' } else { '<host box LAN IP>' })
       LAN Port        = $LanPort
       Timeout seconds = 120   (raise it for the baseline run; 30 masks bugs as timeouts)
  3. Run a scenario from testing/SCENARIOS.md, then:
       .\collect-logs.ps1 -Role $Role -Label <scenario>
"@
if ($Role -eq 'host') {
    $ips = (Get-NetIPAddress -AddressFamily IPv4 |
            Where-Object { $_.IPAddress -notlike '127.*' -and $_.IPAddress -notlike '169.254.*' }).IPAddress
    Write-Host "  This box's LAN IP(s): $($ips -join ', ')" -ForegroundColor Green
}
